config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'leisures/search' => 'leisures#search'
  get 'leisures/:id/like' => 'leisures#like'
  resources :leisures

  get 'users/show/:uid' => 'users#show', as: 'user_show'
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks' ,
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

 

end

app/models/leisure.rb
class Leisure < ActiveRecord::Base
	acts_as_taggable
	has_reputation :likes, source: :user, aggregated_by: :sum
	validates :name, presence: true, uniqueness: true
	validates :tell, :format=>{:with=>/\A[0-9-]/, :allow_blank=>true}

	def self.search(query_name="",query_cat="")
		if query_cat && query_name
			self.where(category: query_cat).where(['name LIKE ?', "%#{query_name}%"])
		elsif query_cat
			self.where(category: query_cat)
		elsif query_name
			self.where(['name LIKE ?', "%#{query_name}%"])
		else
			self.all
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,:omniauthable
  has_many :evaluations, class_name: "ReputationSystem::Evaluation", as: :source

  def self.find_for_oauth(auth)
  	user = User.where(uid: auth.uid, provider: auth.provider).first
  	unless user
  		user = User.create(
  			uid: auth.uid,
  			provider: auth.provider,
  			name: auth.info.name,
        image: auth.info.image,
  			email: User.get_email(auth),
  			password: Devise.friendly_token[4, 30])
  	end
  	user
  end

  def self.liked?(post)
    evaluations.where(target_type: post.class, reputation_name: :likes, target_id: post.id).present?
  end

  private
  def self.get_email(auth)
  	email = auth.info.email
  	email = "#{auth.provider}-#{auth.uid}@example.com" if email.blank?
  	email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :null_session

	private
	def render_error(status, msg)
		render :json => {:message => msg, :status => status}
	end

	def authenticate_#{mapping}!(opts={})
		render_error(401,"Unauthorized") unless user_signed_in?
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/leisures_controller.rb
class LeisuresController < ApplicationController
  before_action :set_leisure, only: [:show, :edit, :update, :destroy, :like]

  # GET /leisures
  def index
    @leisures = Leisure.all
    render_leisures
  end

  def search
    @leisures = Leisure.search(params[:name],params[:cat])
    render_leisures
  end

  # GET /leisures/1
  def show
    render_leisure 200
  end

  #??? GET /leisures/new
  def new
    @leisure = Leisure.new
  end

  #??? GET /leisures/1/edit
  def edit
  end

  # POST /leisures
  def create
    @leisure = Leisure.new(leisure_params)

    if @leisure.save
      render_leisure 201
    else
      render_error(400,@leisure.errors)
    end
  end

  # PATCH/PUT /leisures/1
  def update
    if @leisure.update(leisure_params)
      render_leisure 201
    else
      render_error(400,@leisure.errors)
    end
  end

  def like
    @leisure.add_evaluation(:likes, 1, current_user) unless @leisure.delete_evaluation(:likes, current_user)
    render_leisure 201
    #@leisure.reputation_for(:likes).to_i
  end

  # DELETE /leisures/1
  def destroy
    @leisure.destroy
    render_leisure 201
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leisure
      @leisure = Leisure.find_by_id(params[:id])
      render_error(404,"Not Found") unless @leisure
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leisure_params
      params.require(:leisure).permit(:name, :address, :description)
    end

    def render_leisures
      responce_json = {data:{leisure:[]},status: 200}
      @leisures.each do |l|
        responce_json[:data][:leisure].push({
          id: l.id,
          name: l.name,
          description: l.description,
          address: l.address,
          tell: l.tell,
          hours: l.hours,
          category: l.category,
          tag: l.tag_list,
          like: l.reputation_for(:likes).to_i
          })
      end
      render :json => responce_json
    end

    def render_leisure(status_num)
      responce_json = {
        data: {
          leisure: {
            name: @leisure.name,
            id: @leisure.id,
            description: @leisure.description,
            tell: @leisure.tell,
            hours: @leisure.hours,
            category: @leisure.category,
            tag: @leisure.tag_list,
            like: @leisure.reputation_for(:likes).to_i
          }
          },
          status: status_num
        }
        render :json => responce_json
      end
    end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  private
  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    if @user.persisted?
      cookies.permanent[:xxx_logined] = { value: @user.created_at }
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      if provider == 'twitter'
        session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
      end
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
	def create
		super
	end

	def new
		super
	end

	def edit
		super
	end
	
	def update
		super
	end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	def create
		super
	end

	def new
		super
	end

	def edit
		super
	end
	
	def update
		super
	end

	def cancel
		super
	end

	def destroy
		super
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	def new
		super
	end
	
  def create
    self.resource = warden.authenticate!(auth_options)
    #set_flash_message(:notice, :signed_in) if is_flashing_format?
    sign_in(resource_name, resource)
    #yield resource if block_given?
    #respond_with resource, location: after_sign_in_path_for(resource)
    render :json => { message: :no_content, status: 204}
  end
	
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    #set_flash_message :notice, :signed_out if signed_out && is_flashing_format?
    #yield if block_given?
    #respond_to_on_destroy
    render :json => { message: :no_content, status: 204}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]

  # GET /users/1
  def show
  	user = find_user(params[:uid])
    if user
    	responce_json = {
    		data: {
    			user: {
    				name: user.name,
    				uid: user.uid,
    				provider: user.provider,
    				image: user.image
    			}
    		},
    		status: 200
    	}
    	render :json => responce_json
    end
  end

  private
  def find_user(uid)
    user = User.where(uid: uid).first
    render_error(404,"Not Found") unless user
    return user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leisures_helper.rb
module LeisuresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TestRails</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<p class="navbar-text pull-right">
		<% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong>.
		<%= link_to 'profile', user_show_path(current_user.uid) %>
		<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
		<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
		<%= link_to "facebook", user_omniauth_authorize_path(:facebook) %> |
		<%= link_to "twitter", user_omniauth_authorize_path(:twitter) %>
		<% end %>
	</p>

	<% if notice %>
	<p class="alert alert-notice"><%= notice %></p>
	<% end %>
	<% if alert %>
	<p class="alert alert-error"><%= alert %></p>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/leisures/_form.html.erb
<%= form_for(@leisure) do |f| %>
  <% if @leisure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leisure.errors.count, "error") %> prohibited this leisure from being saved:</h2>

      <ul>
      <% @leisure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leisures/edit.html.erb
<h1>Editing Leisure</h1>

<%= render 'form' %>

<%= link_to 'Show', @leisure %> |
<%= link_to 'Back', leisures_path %>

app/views/leisures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leisures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leisures.each do |leisure| %>
      <tr>
        <td><%= leisure.name %></td>
        <td><%= leisure.address %></td>
        <td><%= link_to 'Show', leisure %></td>
        <td><%= link_to 'Edit', edit_leisure_path(leisure) %></td>
        <td><%= link_to 'Destroy', leisure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leisure', new_leisure_path %>

app/views/leisures/new.html.erb
<h1>New Leisure</h1>

<%= render 'form' %>

<%= link_to 'Back', leisures_path %>

app/views/leisures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @leisure.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @leisure.address %>
</p>

<%= link_to 'Edit', edit_leisure_path(@leisure) %> |
<%= link_to 'Back', leisures_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>